cache_test: Fix flakes in TestDropUpdates
While submitting a documentation PR, CI failed to run my change with
the following flaky error:

    cache_test.go:866:
          Error Trace:  cache_test.go:866
                              cache_test.go:872
          Error:        Should be true
          Test:         TestDropUpdates

This happens because sometimes sleeping for 1 ms is not enough to
ensure the background processing happens. Replace with c.Wait(),
which ensures it waits until everything is processed.

There is a second race, with the full output below. It is caused
when c.Close() is called with the last Set() still in the buffer.
This causes onEvict() to be called for every item. Call c.Wait()
before that point also.

I was able to reproduce these flakes using my "makeflaky" tool:

https://github.com/evanj/hacks#makeflaky-pause-a-process-to-make-tests-flaky

Running it with the following arguments:

    makeflaky -goTest . -race -v -run=TestDropUpdates -count=1000 -failfast

After this change I was unable to reproduce these two flakes.
Unfortunately, I don't know if this test still correctly covers the
race condition it was designed to trigger in the first place.

Full output of the second race:

panic: interface conversion: interface {} is nil, not string [recovered]
  panic: interface conversion: interface {} is nil, not string

goroutine 2383 [running]:
testing.tRunner.func1.2({0x1031b03e0, 0xc0001c4a80})
  go/1.20.2/libexec/src/testing/testing.go:1526 +0x278
testing.tRunner.func1()
  go/1.20.2/libexec/src/testing/testing.go:1529 +0x448
panic({0x1031b03e0, 0xc0001c4a80})
  go/1.20.2/libexec/src/runtime/panic.go:890 +0x248
github.com/dgraph-io/ristretto.TestDropUpdates.func2.1({0xc00041d720?, 0xc00041d720?}, {0x0?, 0x0})
  ristretto/cache_test.go:826 +0x1b8
github.com/dgraph-io/ristretto.TestDropUpdates.func2.2(0xc000514910)
  ristretto/cache_test.go:849 +0x6c
github.com/dgraph-io/ristretto.NewCache.func2(0xc000514910)
  ristretto/cache.go:188 +0x70
github.com/dgraph-io/ristretto.(*Cache).Clear(0xc000234200)
  ristretto/cache.go:388 +0x10c
github.com/dgraph-io/ristretto.(*Cache).Close(0xc000234200)
  ristretto/cache.go:356 +0x5c
github.com/dgraph-io/ristretto.TestDropUpdates.func2()
  ristretto/cache_test.go:867 +0x474
github.com/dgraph-io/ristretto.TestDropUpdates(0xc0001f16c0)
  ristretto/cache_test.go:872 +0xac